### ISSUE TITLE
New version on rubygems.org

### ISSUE THREAD

**Issue by twelvelabs** [gemnasium/gemnasium-gem#11]
Any chance you can push a new version of the gem on rubygems.org?

**Comment by twelvelabs** [comment]
ping @fcat

**Comment by fcat** [comment]
Yes, I will publish a new version on rubygems.org.

**Comment by twelvelabs** [comment]
bump

**Comment by twelvelabs** [comment]
The irony is that I'm asking because https://gemnasium.com/ doesn't track gems pinned to a github repo, and I would like to be notified when there are updates to the `gemnasium` gem.

**Comment by twelvelabs** [comment]
Latest on https://rubygems.org/gems/gemnasium is 3.2 - closing.
